name = "omniroute-master-proxy"
main = "src/index.js"
compatibility_date = "2026-09-04"
workers_dev = true

[placement]
mode = "smart"

[[services]]
binding = "BAI_WORKER"
service = "omniroute-provider-bai"

[[services]]
binding = "DAHL_WORKER"
service = "omniroute-provider-dahl"

[secrets]
required = ["ROUTER_API_KEY"]