name = "omniroute-provider-bai"
main = "src/index.js"
compatibility_date = "2026-09-04"
workers_dev = false

[placement]
mode = "smart"

[vars]
UPSTREAM_BASE_URL = "https://api.b.ai/v1"
AUTH_MODE = "bearer"
ENVIRONMENT = "production"

[[kv_namespaces]]
binding = "KV_USAGE"
id = "66090c4f6fdc476d8a929b9ac1728f26"   # 👈 پس از ایجاد KV، این id را جایگزین کنید

[secrets]
required = ["UPSTREAM_API_KEYS"]